### ISSUE TITLE
Incompatible with BadAssEngi mod

### ISSUE THREAD

**Issue by Poke5555** [JackPendarvesRead/RoR2FluffyMods#3]
https://thunderstore.io/package/xiaoxiao921/BadAssEngi/

with both mods installed placing turrets does not delete old turrets and the newly placed turrets cannot fire.
i imagine this is because with badassengi turrets items automatically update.

**Comment by JackPendarvesRead** [comment]
Sorry, can you please specify exactly which mod it is which is incompatible with BadAssEngi? I have all of the mods in one repo.

**Comment by Poke5555** [comment]
It was infusion stack but you fixed it with ver 5.0.2 i guess this was the problem 

> - Fixed a null reference error which would occur if someone dies without an attacker (e.g. with a console kill command)

**Comment by JackPendarvesRead** [comment]
Thanks for the report.
